version: "3.7"
services: 
    server:
        image: ghcr.io/marcodellemarche/paola-go-bot:${IMAGE_TAG:-latest}
        build:
            dockerfile: Dockerfile
            context: .
        environment:
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_DB=${POSTGRES_DB:-paola-go-bot-db}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - OPENAI_ASSISTANT_ID=${OPENAI_ASSISTANT_ID}
            - OPENAI_LIMITER_CAPACITY=${OPENAI_LIMITER_CAPACITY:-100}
            - OPENAI_LIMITER_RATE_PER_HOUR=${OPENAI_LIMITER_RATE_PER_HOUR:-100}
        restart: always
        depends_on:
            - database
        networks:
            - default
            - backend
        command: "listen"
    database:
        image: postgres:14.5
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_DB=${POSTGRES_DB:-paola-go-bot-db}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes: 
            - data:/var/lib/postgresql/data
        networks:
            - backend
volumes:
    data:
networks:
    backend:
