name: Docker Build and Push Remotely

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "OPENAI_ASSISTANT_ID=${{ secrets.OPENAI_ASSISTANT_ID }}" >> .env
          echo "OPENAI_LIMITER_CAPACITY=${{ secrets.OPENAI_LIMITER_CAPACITY }}" >> .env
          echo "OPENAI_LIMITER_RATE_PER_HOUR=${{ secrets.OPENAI_LIMITER_RATE_PER_HOUR }}" >> .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install dependencies 
        run: |
          apt install -y qemu-user-static binfmt-support

      - name: Build and push Docker image
        run: |
          TAG=$(date +%Y%m%d%H%M)
          docker buildx build --platform linux/arm/v7 --push -t marcodellemarche/paola-go-bot-server:$TAG .
