name: Docker Build and Push Better New

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

env:
  # TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  # POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  # OPENAI_ASSISTANT_ID: ${{ secrets.OPENAI_ASSISTANT_ID }}
  # OPENAI_LIMITER_CAPACITY: ${{ secrets.OPENAI_LIMITER_CAPACITY }}
  # OPENAI_LIMITER_RATE_PER_HOUR: ${{ secrets.OPENAI_LIMITER_RATE_PER_HOUR }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm/v7
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
