name: Remind birthdays

on:
  workflow_dispatch:
  schedule:
    - cron: 00 09/12 * * *

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.16'
      - name: Remind today's birthdays
        run: go run . reminder
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Remind birthdays 3 days in advance
        run: go run . reminder 3
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
